name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    services:
      mysql:
        image: mysql:8.0
        env: 
          MYSQL_DATABASE: test_nopennopaper
          MYSQL_ROOT_PASSWORD: testpw
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
          go-version: '1.22'

    - name: Install dependencies
      run: go get ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
